name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: nix flake check
        run: nix flake check --print-build-logs

      - name: nix build
        run: nix build --print-build-logs

      - name: rb-lite --help
        run: ./result/bin/rb-lite --help
